services:
  - type: web
    name: hospital-backend
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: He thong benh vien
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: hospital-database
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: SEED_DATABASE
        value: "false"

databases:
  - name: hospital-database
    plan: free
    region: singapore
    databaseName: hospital
    user: hospital
